name: body_part_selector
description: A beautiful selector for different body parts
version: 0.2.0
homepage: https://www.whynotmake.it
repository: https://github.com/timcreatedit/body_part_selector

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ">=1.1.0 <2.0.0"
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  rotation_stage: ^0.3.0
  touchable: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  melos: ^1.3.0
  lintervention: ^0.3.1
  build_runner: ^2.4.15
  mocktail: ^1.0.4

flutter:
  assets:
    - packages/body_part_selector/m_front.svg
    - packages/body_part_selector/m_back.svg
